name: geodjango
channels:
  - defaults
dependencies:
  - asgiref=3.2.10=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py37_0
  - cfitsio=3.470=he774522_6
  - curl=7.67.0=h2a8f88b_0
  - django=3.1.2=py_0
  - expat=2.2.9=h33f27b4_2
  - freexl=1.0.5=hfa6e2cd_0
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.5.1=h5770a2b_1
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - intel-openmp=2020.2=254
  - jpeg=9b=hb83a4c4_2
  - kealib=1.4.7=h07cbb95_6
  - krb5=1.16.4=hc04afaa_0
  - libboost=1.67.0=hd9e427e_4
  - libcurl=7.67.0=h2a8f88b_0
  - libgdal=3.0.2=h1155b67_0
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=he5f2a48_4
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.37=h2a8f88b_0
  - libpq=11.2=h3235a2c_0
  - libspatialite=4.3.0a=h7ffb84d_0
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.1.0=h56a325e_0
  - libxml2=2.9.10=h464c3ec_1
  - lz4-c=1.8.1.2=h2fa13f4_0
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.2.0=py37h45dec08_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - numpy=1.19.1=py37h5510c5b_0
  - numpy-base=1.19.1=py37ha3acd2a_0
  - openjpeg=2.3.0=h5ec785f_1
  - openssl=1.1.1h=he774522_0
  - pcre=8.44=ha925a31_0
  - pip=20.2.3=py37_0
  - postgresql=11.2=h3235a2c_0
  - proj=6.2.1=h9f7ef89_0
  - psycopg2=2.8.4=py37h7a1dbc1_0
  - python=3.7.9=h60c2a47_0
  - pytz=2020.1=py_0
  - setuptools=49.6.0=py37_1
  - six=1.15.0=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - sqlparse=0.3.1=py_0
  - tbb=2018.0.5=he980bc4_0
  - tiledb=1.6.3=h7b000aa_0
  - tk=8.6.10=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=py_0
  - wincertstore=0.2=py37_0
  - xerces-c=3.2.3=ha925a31_0
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.3.7=h508b16e_0
  - pip:
    - django-leaflet==0.27.1
    - gdal==3.0.2
    - djangorestframework
    - djangorestframework-gis
prefix: D:\Programs\Anaconda\envs\geodjango
